#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=MODEL_PROFILING
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=logs/output_%A.out
#SBATCH --error=logs/error_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate dl2023

root=/scratch-local/$USER
mkdir -p $root

code_dir=./

jupyter nbconvert --to notebook --execute DL1_Assignment2_Q1_1.ipynb
